var CORREOS_REM = [
  'administracion@kabzo.org>',
  'asistente.admin@kabzo.org>',
  'disenografico@produccionesdobleb.com>',
  'juridico5@kabzo.org>',
  'juridico7@kabzo.org>',
  'juridico10@kabzo.org>',
  'juridico4@kabzo.org>',
  'juridico12@kabzo.org>',
  'juridico8@kabzo.org>',
  'juridico3@kabzo.org>',
  'cobranza@kabzo.org>',
  'cobranza3@kabzo.org>',
  'dir.contable@kabzo.org>',
  'contabilidad4@kabzo.org>',
  'contabilidad1@kabzo.org>',
  'contabilidad14@kabzo.org>',
  'contabilidad18@kabzo.org>',
  'contabilidad10@kabzo.org>',
  'contabilidad12@kabzo.org>',
  'contabilidad7@kabzo.org>',
  'contabilidad15@kabzo.org>',
  'contabilidad16@kabzo.org>',
  'contabilidad5@kabzo.org>',
  'contabilidad9@kabzo.org>',
  'juridico15@kabzo.org>',
  'juridico9@kabzo.org>',
  'paqueteria2@kabzo.org>',
  'facturacion@kabzo.org>',
  'respaldofacturacion@kabzo.org>',
  'facturacion1@kabzo.org>',
  'facturacion2@kabzo.org>',
  'mensajeria5@kabzo.org>',
  'avisosfacturacion@kabzo.org>',
  'mensajeria13@kabzo.org>',
  'mensajeria7@kabzo.org>',
  'mensajeria3@kabzo.org>',
  'mensajeria10@kabzo.org>',
  'mensajeria2@kabzo.org>',
  'mensajeria15@kabzo.org>',
  'mensajeria4@kabzo.org>',
  'facturacioninterna@kabzo.org>',
  'mensajeria1@kabzo.org>',
  'mensajeria16@kabzo.org>',
  'facturacioninterna2@kabzo.org>',
  'mensajeria11@kabzo.org>',
  'mensajeria9@kabzo.org>',
  'mensajeria6@kabzo.org>',
  'asistente2.admin@kabzo.org>',
  'logistica8@kabzo.org>',
  'asistente.educativa@kabzo.org>',
  'imss@kabzo.org>',
  'contabilidad3@kabzo.org>',
  'finiquitos@kabzo.org>',
  'auxiliarimss@rhfinder.com>',
  'juridico1@kabzo.org>',
  'juridico6@kabzo.org>',
  'logistica3@kabzo.org>',
  'logistica4@kabzo.org>',
  'logistica2@kabzo.org>',
  'pagos@kabzo.org>',
  'receptor@kabzo.org>',
  'asistencia@kabzo.org>',
  'servicios@kabzo.org>',
  'consultores@kabzo.org>',
  'asesores@kabzo.org>',
  'atencion@kabzo.org>',
  'contacto@kabzo.org>',
  'pagos31@kabzo.org>',
  'pagos10@kabzo.org>',
  'pagos25@kabzo.org>',
  'pagos20@kabzo.org>',
  'pagos18@kabzo.org>',
  'pagos4@kabzo.org>',
  'pagos1@kabzo.org>',
  'pagos15@kabzo.org>',
  'pagos24@kabzo.org>',
  'pagos7@kabzo.org>',
  'pagos21@kabzo.org>',
  'pagos32@kabzo.org>',
  'pagos30@kabzo.org>',
  'pagos11@kabzo.org>',
  'pagos22@kabzo.org>',
  'pagos5@kabzo.org>',
  'operacioncarso@gmail.com>',
  'pagos33@kabzo.org>',
  'pagos6@kabzo.org>',
  'pagos14@kabzo.org>',
  'pagos29@kabzo.org>',
  'asesorescarso1@gmail.com>',
  'gastos@kabzo.org>',
  'administracionempresarial1@rhfinder.com>',
  'administracionempresarial@rhfinder.com>',
  'administracionempresarial4@rhfinder.com>',
  'administracionempresarial6@rhfinder.com>',
  'administracionempresarial5@rhfinder.com>',
  'administracionempresarial3@rhfinder.com>',
  'projectmanager@kabzo.org>',
  'sistemas3@kabzo.org>',
  'analistaprocesos2@kabzo.org>',
  'desarrollo@kabzo.org>',
  'optimizacion@kabzo.org>',
  'desarrolladorjr@kabzo.org>',
  'auxproyectos@kabzo.org>',
  'direccion@rhfinder.com>',
  'reclutamiento2@rhfinder.com>',
  'sistemas2@kabzo.org>',
  'sistemas5@kabzo.org>',
  'tesoreria1@kabzo.org>',
  'tesorerias3@kabzo.org>',
  'tesoreriag@kabzo.org>',
  'tesoreriar@kabzo.org>',
  'tesoreria7@kabzo.org>',
  'tesoreria3@kabzo.org>',
  'entregas.guadalajara1@kabzo.org>',
  'tesoreria5@kabzo.org>',
  'tesoreria8@kabzo.org>',
  'facturacion.asesores.pdc@gmail.com>',
  'verificador@kabzo.org>',
  'verificador2@kabzo.org>',
  'verificador1@consultoriavrf.com>',
  'verificador3@consultoriavrf.com>',
  'verificador5@consultoriavrf.com>',
  'verificador8@consultoriavrf.com>',
  'verificador6@consultoriavrf.com>',
  'verificador10@consultoriavrf.com>',
  'verificador9@consultoriavrf.com>',
  'verificador4@consultoriavrf.com>',
  'verificador11@kabzo.org>'
]

var CORREOS_KABZO = {
  'administracion@kabzo.org>': { NOMBRE: 'MARIA_DE_LOS_ANGELES_TREVIÑO_GARCIA', PUESTO: 'DIRECTOR'},
  'asistente.admin@kabzo.org>': { NOMBRE: 'DARLIN_LIZETH_APONTE_VALCARCEL', PUESTO: 'STAFF'},
  'disenografico@produccionesdobleb.com>': { NOMBRE: 'CYNTHIA_ISABEL_GONZALEZ_RAMIREZ', PUESTO: 'STAFF'},
  'juridico5@kabzo.org>': { NOMBRE: 'NANCY_ALEJANDRA_JASSO_MARTINEZ', PUESTO: 'DIRECTOR'},
  'juridico7@kabzo.org>': { NOMBRE: 'BRENDA_SALDIVAR_SILVA', PUESTO: 'SUPERVISOR'},
  'juridico10@kabzo.org>': { NOMBRE: 'EVELYN_TAMEZ_GARZA', PUESTO: 'LIDER'},
  'juridico4@kabzo.org>': { NOMBRE: 'ALAN_ALFREDO_SANCHEZ_LOPEZ', PUESTO: 'STAFF'},
  'juridico12@kabzo.org>': { NOMBRE: 'JESUS_ALBERTO_LEON_DURAN', PUESTO: 'STAFF'},
  'juridico8@kabzo.org>': { NOMBRE: 'LIZETH_YADIRA_CARDENAS_CASTRO', PUESTO: 'STAFF'},
  'juridico3@kabzo.org>': { NOMBRE: 'ALAN_JAHIR_GONZALEZ_MIRANDA', PUESTO: 'STAFF'},
  'cobranza@kabzo.org>': { NOMBRE: 'KEVIN_MORENO_DE_LA_ROSA', PUESTO: 'SUPERVISOR'},
  'cobranza3@kabzo.org>': { NOMBRE: 'LIZBETH_ULAY_MARTINEZ_SILVA', PUESTO: 'STAFF'},
  'dir.contable@kabzo.org>': { NOMBRE: 'PERLA_JANETH_ESPINOZA_GONZALEZ', PUESTO: 'DIRECTOR'},
  'contabilidad4@kabzo.org>': { NOMBRE: 'PERLA_JANETH_ESPINOZA_GONZALEZ', PUESTO: 'DIRECTOR'},
  'contabilidad1@kabzo.org>': { NOMBRE: 'ISAIRA_MORANTES_MONTERO', PUESTO: 'SUPERVISOR'},
  'contabilidad14@kabzo.org>': { NOMBRE: 'FELIX_AARON_NAJERA_LOZA', PUESTO: 'LIDER'},
  'contabilidad18@kabzo.org>': { NOMBRE: 'VICTOR_ALEJANDRO_RUIZ', PUESTO: 'LIDER'},
  'contabilidad10@kabzo.org>': { NOMBRE: 'LUIS_JAVIER_ALANIS_ESCAMILLA', PUESTO: 'STAFF'},
  'contabilidad12@kabzo.org>': { NOMBRE: 'JULIO_CESAR_RANGEL_LOZA', PUESTO: 'STAFF'},
  'contabilidad7@kabzo.org>': { NOMBRE: 'RICARDO_RODRIGUEZ_FERNANDEZ', PUESTO: 'STAFF'},
  'contabilidad15@kabzo.org>': { NOMBRE: 'JAVIER_DE_JESUS_LLADO_PAZ', PUESTO: 'STAFF'},
  'contabilidad16@kabzo.org>': { NOMBRE: 'HUMBERTO_MARTINEZ_MORALES', PUESTO: 'STAFF'},
  'contabilidad5@kabzo.org>': { NOMBRE: 'GONZALO_GONZALEZ_ALONSO', PUESTO: 'STAFF'},
  'contabilidad9@kabzo.org>': { NOMBRE: 'ARELY_SARAHI_DIAZ_GARZA', PUESTO: 'STAFF'},
  'juridico15@kabzo.org>': { NOMBRE: 'MIKEL_GARZA_CARRILLO', PUESTO: 'SUPERVISOR'},
  'juridico9@kabzo.org>': { NOMBRE: 'CINTHIA_GABRIELA_OVIEDO_ESPINOZA', PUESTO: 'LIDER'},
  'paqueteria2@kabzo.org>': { NOMBRE: 'TERESA_MONTIEL_CASTILLO', PUESTO: 'STAFF'},
  'facturacion@kabzo.org>': { NOMBRE: 'SAMANTHA_REYNA_FLORES', PUESTO: 'SUPERVISOR'},
  'respaldofacturacion@kabzo.org>': { NOMBRE: 'SAMANTHA_REYNA_FLORES', PUESTO: 'SUPERVISOR'},
  'facturacion1@kabzo.org>': { NOMBRE: 'JOSE_JULIAN_ACOSTA_RODRIGUEZ', PUESTO: 'LIDER'},
  'facturacion2@kabzo.org>': { NOMBRE: 'EDGAR_RODRIGUEZ_SILVA', PUESTO: 'LIDER'},
  'mensajeria5@kabzo.org>': { NOMBRE: 'WENDY_YARESY_VALDEZ_VALDEZ', PUESTO: 'STAFF'},
  'avisosfacturacion@kabzo.org>': { NOMBRE: 'ANDREA_NICOLE_CANTU_OROZCO', PUESTO: 'STAFF'},
  'mensajeria13@kabzo.org>': { NOMBRE: 'FRANCISCO_EDUARDO_GAYTAN', PUESTO: 'STAFF'},
  'mensajeria7@kabzo.org>': { NOMBRE: 'JULIO_ALBERTO_MATA', PUESTO: 'STAFF'},
  'mensajeria3@kabzo.org>': { NOMBRE: 'BRENDA_FABIOLA_GANDARA', PUESTO: 'STAFF'},
  'mensajeria10@kabzo.org>': { NOMBRE: 'JORGE_ALEJANDRO_ALMAGUER_GANDARA', PUESTO: 'STAFF'},
  'mensajeria2@kabzo.org>': { NOMBRE: 'DANIEL_MARROQUIN_MARROQUIN', PUESTO: 'STAFF'},
  'mensajeria15@kabzo.org>': { NOMBRE: 'DANIEL_ALEJANDRO_MENDOZA_ESQUIVEL', PUESTO: 'STAFF'},
  'mensajeria4@kabzo.org>': { NOMBRE: 'JAVIER_IRAM_MARTINEZ_TAMEZ', PUESTO: 'STAFF'},
  'facturacioninterna@kabzo.org>': { NOMBRE: 'ERNESTO_RODRIGUEZ_ALVAREZ', PUESTO: 'STAFF'},
  'mensajeria1@kabzo.org>': { NOMBRE: 'AARON_GARCIA_VALDEZ', PUESTO: 'STAFF'},
  'mensajeria16@kabzo.org>': { NOMBRE: 'DIEGO_EDUARDO_ELICERIO_VARGAS', PUESTO: 'STAFF'},
  'facturacioninterna2@kabzo.org>': { NOMBRE: 'HUMBERTO_ALANIS_SIERRA', PUESTO: 'STAFF'},
  'mensajeria11@kabzo.org>': { NOMBRE: 'XIMENA_REYNA_FLORES', PUESTO: 'STAFF'},
  'mensajeria9@kabzo.org>': { NOMBRE: 'ROBERTO_LEAL_TAPIA', PUESTO: 'STAFF'},
  'mensajeria6@kabzo.org>': { NOMBRE: 'ALEXIS_ADRIAN_CASAS_TORRES', PUESTO: 'STAFF'},
  'asistente2.admin@kabzo.org>': { NOMBRE: 'EVAMARIA_SUAREZ_BARRON', PUESTO: 'SUPERVISOR'},
  'logistica8@kabzo.org>': { NOMBRE: 'DIEGO_ARMANDO_HERRERA_SALAS', PUESTO: 'STAFF'},
  'asistente.educativa@kabzo.org>': { NOMBRE: 'ALEJANDRA_SILVA_GARCIA', PUESTO: 'STAFF'},
  'imss@kabzo.org>': { NOMBRE: 'ISAMAR_GUTIERREZ_BALDERAS', PUESTO: 'LIDER'},
  'contabilidad3@kabzo.org>': { NOMBRE: 'ISAMAR_GUTIERREZ_BALDERAS', PUESTO: 'LIDER'},
  'finiquitos@kabzo.org>': { NOMBRE: 'ISAMAR_GUTIERREZ_BALDERAS', PUESTO: 'LIDER'},
  'auxiliarimss@rhfinder.com>': { NOMBRE: 'ESTEFANIA_GAYTAN_CONTRERAS', PUESTO: 'STAFF'},
  'juridico1@kabzo.org>': { NOMBRE: 'ALONDRA_MARIBEL_VARGAS_TENEYUQUE', PUESTO: 'SUPERVISOR'},
  'juridico6@kabzo.org>': { NOMBRE: 'LESLY_MICHELLE_SALINAS_IBARRA', PUESTO: 'STAFF'},
  'logistica3@kabzo.org>': { NOMBRE: 'CARLOS_CAVAZOS_LEAL', PUESTO: 'DIRECTOR'},
  'logistica4@kabzo.org>': { NOMBRE: 'EMILIO_GUADALUPE_TORRES_SALINAS', PUESTO: 'SUPERVISOR'},
  'logistica2@kabzo.org>': { NOMBRE: 'JUAN_LUIS_SOLIS_CAVAZOS', PUESTO: 'LIDER'},
  'pagos@kabzo.org>': { NOMBRE: 'YESSICA_CAVAZOS_LEAL', PUESTO: 'DIRECTOR'},
  'receptor@kabzo.org>': { NOMBRE: 'FERNANDO_SALDAÑA_DE_LA_ROSA', PUESTO: 'SUPERVISOR'},
  'asistencia@kabzo.org>': { NOMBRE: 'ALONDRA_MATA_FLORES', PUESTO: 'LIDER'},
  'servicios@kabzo.org>': { NOMBRE: 'FRANCISCO_EDUARDO_GAYTAN', PUESTO: 'STAFF'},
  'consultores@kabzo.org>': { NOMBRE: 'REYNALDO_SANTOS_MORENO', PUESTO: 'LIDER'},
  'asesores@kabzo.org>': { NOMBRE: 'MARTIN_OVIDIO_TAMEZ_TAMEZ', PUESTO: 'LIDER'},
  'atencion@kabzo.org>': { NOMBRE: 'JOSE_ANDRES_NIETO_JUAREZ', PUESTO: 'LIDER'},
  'contacto@kabzo.org>': { NOMBRE: 'MIGUEL_ANGEL_LOZANO', PUESTO: 'LIDER'},
  'pagos31@kabzo.org>': { NOMBRE: 'RICARDO_RAMIREZ_SEGOVIA', PUESTO: 'STAFF'},
  'pagos10@kabzo.org>': { NOMBRE: 'ULISES_FELIX_FLORES_CASTILLO', PUESTO: 'STAFF'},
  'pagos25@kabzo.org>': { NOMBRE: 'MIRIAM_REBECA_VILLARREAL_LUNA', PUESTO: 'STAFF'},
  'pagos20@kabzo.org>': { NOMBRE: 'SANDRA_ELIZABETH_VARGAS_GARCIA', PUESTO: 'STAFF'},
  'pagos18@kabzo.org>': { NOMBRE: 'ANGELES_SARAIN_RIVAS_ELIAS', PUESTO: 'STAFF'},
  'pagos4@kabzo.org>': { NOMBRE: 'MIGUEL_FERNANDO_REYNA_ROCHA', PUESTO: 'STAFF'},
  'pagos1@kabzo.org>': { NOMBRE: 'MELISA_ALEJANDRA_RANGEL_BUSTOS', PUESTO: 'STAFF'},
  'pagos15@kabzo.org>': { NOMBRE: 'IRVIN_ABDIEL_RUEDA_CARRIZALEZ', PUESTO: 'STAFF'},
  'pagos24@kabzo.org>': { NOMBRE: 'JORGE_ELIUD_PEREZ_LEIJA', PUESTO: 'STAFF'},
  'pagos7@kabzo.org>': { NOMBRE: 'SARA_MARIA_GONZALEZ_BRIAGAS', PUESTO: 'STAFF'},
  'pagos21@kabzo.org>': { NOMBRE: 'EDWIN_JASSIEL_GARZA_MARTINEZ', PUESTO: 'STAFF'},
  'pagos32@kabzo.org>': { NOMBRE: 'ELUID_FELIX_FLORES_CASTILLO', PUESTO: 'STAFF'},
  'pagos30@kabzo.org>': { NOMBRE: 'JOSE_GUADALUPE_RODRIGUEZ', PUESTO: 'STAFF'},
  'pagos11@kabzo.org>': { NOMBRE: 'RUBEN_VITAL_BETANCOURT', PUESTO: 'STAFF'},
  'pagos22@kabzo.org>': { NOMBRE: 'ROCIO_ELIZABETH_VAZQUEZ_LOPEZ', PUESTO: 'STAFF'},
  'pagos5@kabzo.org>': { NOMBRE: 'EYMI_AYLIN_RAYAS_SANTOS', PUESTO: 'STAFF'},
  'operacioncarso@gmail.com>': { NOMBRE: 'AZENETH_SANCHEZ_VALDEZ', PUESTO: 'STAFF'},
  'pagos33@kabzo.org>': { NOMBRE: 'LESLIE_JEANNETH_SALAZAR_SILVA', PUESTO: 'STAFF'},
  'pagos6@kabzo.org>': { NOMBRE: 'FRANCISCO_CAVAZOS_LEAL', PUESTO: 'LIDER'},
  'pagos14@kabzo.org>': { NOMBRE: 'YULIANA_LIZETH_RUEDA_CARRIZALES', PUESTO: 'STAFF'},
  'pagos29@kabzo.org>': { NOMBRE: 'NAYLA_VERANIA_SANTOS_MORENO', PUESTO: 'STAFF'},
  'asesorescarso1@gmail.com>': { NOMBRE: 'ARANZA', PUESTO: 'STAFF'},
  'gastos@kabzo.org>': { NOMBRE: 'EMELY_RUBI_CARMONA_VALDEZ', PUESTO: 'SUPERVISOR'},
  'administracionempresarial1@rhfinder.com>': { NOMBRE: 'VALERIA_ALEJANDRA_VARGAS_GARCIA', PUESTO: 'LIDER'},
  'administracionempresarial@rhfinder.com>': { NOMBRE: 'CLARA_NATALIE_REYNA_ROCHA', PUESTO: 'LIDER'},
  'administracionempresarial4@rhfinder.com>': { NOMBRE: 'NADIA_ISELA_ELIZONDO_TREVIÑO', PUESTO: 'STAFF'},
  'administracionempresarial6@rhfinder.com>': { NOMBRE: 'FRIDA_DENISSE_PIÑA_GOMEZ', PUESTO: 'STAFF'},
  'administracionempresarial5@rhfinder.com>': { NOMBRE: 'NANCY_NAYELI_LUNA_AREVALO', PUESTO: 'STAFF'},
  'administracionempresarial3@rhfinder.com>': { NOMBRE: 'FATIMA_LUCIA_MARTINEZ_RODRIGUEZ', PUESTO: 'STAFF'},
  'projectmanager@kabzo.org>': { NOMBRE: 'SARAI_BELLO_ALBARRAN', PUESTO: 'SUPERVISOR'},
  'sistemas3@kabzo.org>': { NOMBRE: 'DAVID_JORGE_TAMEZ_SALDIVAR', PUESTO: 'LIDER'},
  'analistaprocesos2@kabzo.org>': { NOMBRE: 'JONATHAN_BERNARDO_SOTO_GONZALEZ', PUESTO: 'STAFF'},
  'desarrollo@kabzo.org>': { NOMBRE: 'JUAN_BAUTISTA_HERNANDEZ', PUESTO: 'LIDER'},
  'optimizacion@kabzo.org>': { NOMBRE: 'MONICA_ANAHI_AGUILAR_GONZALEZ', PUESTO: 'STAFF'},
  'desarrolladorjr@kabzo.org>': { NOMBRE: 'GUSTAVO_ALBERTO_SANCHEZ_ROCHA', PUESTO: 'STAFF'},
  'auxproyectos@kabzo.org>': { NOMBRE: 'JORGE_LUIS_MORAN_VALENZUELA', PUESTO: 'STAFF'},
  'direccion@rhfinder.com>': { NOMBRE: 'CLAUDIA_GABRIELA_LEAL_GONZALEZ', PUESTO: 'SUPERVISOR'},
  'reclutamiento2@rhfinder.com>': { NOMBRE: 'STEPHANIE_LIZBETH_LOZANO_HERNANDEZ', PUESTO: 'STAFF'},
  'sistemas2@kabzo.org>': { NOMBRE: 'JOSE_OMAR_VILLALOBOS_SALINAS', PUESTO: 'LIDER'},
  'sistemas5@kabzo.org>': { NOMBRE: 'JESUS_ALFONSO_AYALA_FLORES', PUESTO: 'STAFF'},
  'tesoreria1@kabzo.org>': { NOMBRE: 'CARMEN_GABRIELA_GONZALEZ_GONZALEZ', PUESTO: 'DIRECTOR'},
  'tesorerias3@kabzo.org>': { NOMBRE: 'SERGIO_SALAS_SALAZAR', PUESTO: 'SUPERVISOR'},
  'tesoreriag@kabzo.org>': { NOMBRE: 'LIZETH_VERONICA_AYALA_AGUILAR', PUESTO: 'LIDER'},
  'tesoreriar@kabzo.org>': { NOMBRE: 'YOWALY_VAZQUEZ_VALDEZ', PUESTO: 'LIDER'},
  'tesoreria7@kabzo.org>': { NOMBRE: 'CARLOS_ALMAGUER_SALAZAR', PUESTO: 'STAFF'},
  'tesoreria3@kabzo.org>': { NOMBRE: 'MARIA_DOLORES_VILLAGOMEZ', PUESTO: 'STAFF'},
  'entregas.guadalajara1@kabzo.org>': { NOMBRE: 'JESSICA_LILIANA_LAU_CONTRERAS', PUESTO: 'STAFF'},
  'tesoreria5@kabzo.org>': { NOMBRE: 'CYNTHIA_JANETH_ALANIS_SUAREZ', PUESTO: 'STAFF'},
  'tesoreria8@kabzo.org>': { NOMBRE: 'ARNOLD_ANTONIO_VAZQUEZ_VALDES', PUESTO: 'STAFF'},
  'facturacion.asesores.pdc@gmail.com>': { NOMBRE: 'JUAN_JESUS_GARCIA_ALANIS', PUESTO: 'STAFF'},
  'verificador@kabzo.org>': { NOMBRE: 'AZAEL_RANGEL_RODRIGUEZ', PUESTO: 'DIRECTOR'},
  'verificador2@kabzo.org>': { NOMBRE: 'DAMARIS_TORRES_OLIVARES', PUESTO: 'SUPERVISOR'},
  'verificador1@consultoriavrf.com>': { NOMBRE: 'JULIAN_LOZANO_GARZA', PUESTO: 'LIDER'},
  'verificador3@consultoriavrf.com>': { NOMBRE: 'FLOR_THALIA_MEDINA_GALLEGOS', PUESTO: 'LIDER'},
  'verificador5@consultoriavrf.com>': { NOMBRE: 'LUIS_GERARDO_PEÑA_BELTRAN', PUESTO: 'STAFF'},
  'verificador8@consultoriavrf.com>': { NOMBRE: 'ANDREA_FLORES_LOZANO', PUESTO: 'STAFF'},
  'verificador6@consultoriavrf.com>': { NOMBRE: 'DANIELA_NOHEMI_GONZALEZ_TORRES', PUESTO: 'STAFF'},
  'verificador10@consultoriavrf.com>': { NOMBRE: 'MANUEL_ENRIQUE_MENDOZA_ESQUIVE', PUESTO: 'STAFF'},
  'verificador9@consultoriavrf.com>': { NOMBRE: 'BRISEIDA_JACKELINE_ZAPATA_SANCHEZ', PUESTO: 'STAFF'},
  'verificador4@consultoriavrf.com>': { NOMBRE: 'NAZIRA_YARESSI_JAIME_MARTINEZ', PUESTO: 'STAFF'},
  'verificador11@kabzo.org>': { NOMBRE: 'PEDRO_SUAREZ_BARRON', PUESTO: 'STAFF'},
}

var USERS = {
  'administracion@kabzo.org': 'MARIA_DE_LOS_ANGELES_TREVIÑO_GARCIA',
  'asistente.admin@kabzo.org': 'DARLIN_LIZETH_APONTE_VALCARCEL',
  'disenografico@produccionesdobleb.com': 'CYNTHIA_ISABEL_GONZALEZ_RAMIREZ',
  'juridico5@kabzo.org': 'NANCY_ALEJANDRA_JASSO_MARTINEZ',
  'juridico7@kabzo.org': 'BRENDA_SALDIVAR_SILVA',
  'juridico10@kabzo.org': 'EVELYN_TAMEZ_GARZA',
  'juridico4@kabzo.org': 'ALAN_ALFREDO_SANCHEZ_LOPEZ',
  'juridico12@kabzo.org': 'JESUS_ALBERTO_LEON_DURAN',
  'juridico8@kabzo.org': 'LIZETH_YADIRA_CARDENAS_CASTRO',
  'juridico3@kabzo.org': 'ALAN_JAHIR_GONZALEZ_MIRANDA',
  'cobranza@kabzo.org': 'KEVIN_MORENO_DE_LA_ROSA',
  'cobranza3@kabzo.org': 'LIZBETH_ULAY_MARTINEZ_SILVA',
  'dir.contable@kabzo.org': 'PERLA_JANETH_ESPINOZA_GONZALEZ',
  'contabilidad4@kabzo.org': 'PERLA_JANETH_ESPINOZA_GONZALEZ',
  'contabilidad1@kabzo.org': 'ISAIRA_MORANTES_MONTERO',
  'contabilidad14@kabzo.org': 'FELIX_AARON_NAJERA_LOZA',
  'contabilidad18@kabzo.org': 'VICTOR_ALEJANDRO_RUIZ',
  'contabilidad10@kabzo.org': 'LUIS_JAVIER_ALANIS_ESCAMILLA',
  'contabilidad12@kabzo.org': 'JULIO_CESAR_RANGEL_LOZA',
  'contabilidad7@kabzo.org': 'RICARDO_RODRIGUEZ_FERNANDEZ',
  'contabilidad15@kabzo.org': 'JAVIER_DE_JESUS_LLADO_PAZ',
  'contabilidad16@kabzo.org': 'HUMBERTO_MARTINEZ_MORALES',
  'contabilidad5@kabzo.org': 'GONZALO_GONZALEZ_ALONSO',
  'contabilidad9@kabzo.org': 'ARELY_SARAHI_DIAZ_GARZA',
  'juridico15@kabzo.org': 'MIKEL_GARZA_CARRILLO',
  'juridico9@kabzo.org': 'CINTHIA_GABRIELA_OVIEDO_ESPINOZA',
  'paqueteria2@kabzo.org': 'TERESA_MONTIEL_CASTILLO',
  'facturacion@kabzo.org': 'SAMANTHA_REYNA_FLORES',
  'respaldofacturacion@kabzo.org': 'SAMANTHA_REYNA_FLORES',
  'facturacion1@kabzo.org': 'JOSE_JULIAN_ACOSTA_RODRIGUEZ',
  'facturacion2@kabzo.org': 'EDGAR_RODRIGUEZ_SILVA',
  'mensajeria5@kabzo.org': 'WENDY_YARESY_VALDEZ_VALDEZ',
  'avisosfacturacion@kabzo.org': 'ANDREA_NICOLE_CANTU_OROZCO',
  'mensajeria13@kabzo.org': 'FRANCISCO_EDUARDO_GAYTAN',
  'mensajeria7@kabzo.org': 'JULIO_ALBERTO_MATA',
  'mensajeria3@kabzo.org': 'BRENDA_FABIOLA_GANDARA',
  'mensajeria10@kabzo.org': 'JORGE_ALEJANDRO_ALMAGUER_GANDARA',
  'mensajeria2@kabzo.org': 'DANIEL_MARROQUIN_MARROQUIN',
  'mensajeria15@kabzo.org': 'DANIEL_ALEJANDRO_MENDOZA_ESQUIVEL',
  'mensajeria4@kabzo.org': 'JAVIER_IRAM_MARTINEZ_TAMEZ',
  'facturacioninterna@kabzo.org': 'ERNESTO_RODRIGUEZ_ALVAREZ',
  'mensajeria1@kabzo.org': 'AARON_GARCIA_VALDEZ',
  'mensajeria16@kabzo.org': 'DIEGO_EDUARDO_ELICERIO_VARGAS',
  'facturacioninterna2@kabzo.org': 'HUMBERTO_ALANIS_SIERRA',
  'mensajeria11@kabzo.org': 'XIMENA_REYNA_FLORES',
  'mensajeria9@kabzo.org': 'ROBERTO_LEAL_TAPIA',
  'mensajeria6@kabzo.org': 'ALEXIS_ADRIAN_CASAS_TORRES',
  'asistente2.admin@kabzo.org': 'EVAMARIA_SUAREZ_BARRON',
  'logistica8@kabzo.org': 'DIEGO_ARMANDO_HERRERA_SALAS',
  'asistente.educativa@kabzo.org': 'ALEJANDRA_SILVA_GARCIA',
  'imss@kabzo.org': 'ISAMAR_GUTIERREZ_BALDERAS',
  'contabilidad3@kabzo.org': 'ISAMAR_GUTIERREZ_BALDERAS',
  'finiquitos@kabzo.org': 'ISAMAR_GUTIERREZ_BALDERAS',
  'auxiliarimss@rhfinder.com': 'ESTEFANIA_GAYTAN_CONTRERAS',
  'juridico1@kabzo.org': 'ALONDRA_MARIBEL_VARGAS_TENEYUQUE',
  'juridico6@kabzo.org': 'LESLY_MICHELLE_SALINAS_IBARRA',
  'logistica3@kabzo.org': 'CARLOS_CAVAZOS_LEAL',
  'logistica4@kabzo.org': 'EMILIO_GUADALUPE_TORRES_SALINAS',
  'logistica2@kabzo.org': 'JUAN_LUIS_SOLIS_CAVAZOS',
  'pagos@kabzo.org': 'YESSICA_CAVAZOS_LEAL',
  'receptor@kabzo.org': 'FERNANDO_SALDAÑA_DE_LA_ROSA',
  'asistencia@kabzo.org': 'ALONDRA_MATA_FLORES',
  'servicios@kabzo.org': 'FRANCISCO_EDUARDO_GAYTAN',
  'consultores@kabzo.org': 'REYNALDO_SANTOS_MORENO',
  'asesores@kabzo.org': 'MARTIN_OVIDIO_TAMEZ_TAMEZ',
  'atencion@kabzo.org': 'JOSE_ANDRES_NIETO_JUAREZ',
  'contacto@kabzo.org': 'MIGUEL_ANGEL_LOZANO',
  'pagos31@kabzo.org': 'RICARDO_RAMIREZ_SEGOVIA',
  'pagos10@kabzo.org': 'ULISES_FELIX_FLORES_CASTILLO',
  'pagos25@kabzo.org': 'MIRIAM_REBECA_VILLARREAL_LUNA',
  'pagos20@kabzo.org': 'SANDRA_ELIZABETH_VARGAS_GARCIA',
  'pagos18@kabzo.org': 'ANGELES_SARAIN_RIVAS_ELIAS',
  'pagos4@kabzo.org': 'MIGUEL_FERNANDO_REYNA_ROCHA',
  'pagos1@kabzo.org': 'MELISA_ALEJANDRA_RANGEL_BUSTOS',
  'pagos15@kabzo.org': 'IRVIN_ABDIEL_RUEDA_CARRIZALEZ',
  'pagos24@kabzo.org': 'JORGE_ELIUD_PEREZ_LEIJA',
  'pagos7@kabzo.org': 'SARA_MARIA_GONZALEZ_BRIAGAS',
  'pagos21@kabzo.org': 'EDWIN_JASSIEL_GARZA_MARTINEZ',
  'pagos32@kabzo.org': 'ELUID_FELIX_FLORES_CASTILLO',
  'pagos30@kabzo.org': 'JOSE_GUADALUPE_RODRIGUEZ',
  'pagos11@kabzo.org': 'RUBEN_VITAL_BETANCOURT',
  'pagos22@kabzo.org': 'ROCIO_ELIZABETH_VAZQUEZ_LOPEZ',
  'pagos5@kabzo.org': 'EYMI_AYLIN_RAYAS_SANTOS',
  'operacioncarso@gmail.com': 'AZENETH_SANCHEZ_VALDEZ',
  'pagos33@kabzo.org': 'LESLIE_JEANNETH_SALAZAR_SILVA',
  'pagos6@kabzo.org': 'FRANCISCO_CAVAZOS_LEAL',
  'pagos14@kabzo.org': 'YULIANA_LIZETH_RUEDA_CARRIZALES',
  'pagos29@kabzo.org': 'NAYLA_VERANIA_SANTOS_MORENO',
  'asesorescarso1@gmail.com': 'ARANZA',
  'gastos@kabzo.org': 'EMELY_RUBI_CARMONA_VALDEZ',
  'administracionempresarial1@rhfinder.com': 'VALERIA_ALEJANDRA_VARGAS_GARCIA',
  'administracionempresarial@rhfinder.com': 'CLARA_NATALIE_REYNA_ROCHA',
  'administracionempresarial4@rhfinder.com': 'NADIA_ISELA_ELIZONDO_TREVIÑO',
  'administracionempresarial6@rhfinder.com': 'FRIDA_DENISSE_PIÑA_GOMEZ',
  'administracionempresarial5@rhfinder.com': 'NANCY_NAYELI_LUNA_AREVALO',
  'administracionempresarial3@rhfinder.com': 'FATIMA_LUCIA_MARTINEZ_RODRIGUEZ',
  'projectmanager@kabzo.org': 'SARAI_BELLO_ALBARRAN',
  'sistemas3@kabzo.org': 'DAVID_JORGE_TAMEZ_SALDIVAR',
  'analistaprocesos2@kabzo.org': 'JONATHAN_BERNARDO_SOTO_GONZALEZ',
  'desarrollo@kabzo.org': 'JUAN_BAUTISTA_HERNANDEZ',
  'optimizacion@kabzo.org': 'MONICA_ANAHI_AGUILAR_GONZALEZ',
  'desarrolladorjr@kabzo.org': 'GUSTAVO_ALBERTO_SANCHEZ_ROCHA',
  'auxproyectos@kabzo.org': 'JORGE_LUIS_MORAN_VALENZUELA',
  'direccion@rhfinder.com': 'CLAUDIA_GABRIELA_LEAL_GONZALEZ',
  'reclutamiento2@rhfinder.com': 'STEPHANIE_LIZBETH_LOZANO_HERNANDEZ',
  'sistemas2@kabzo.org': 'JOSE_OMAR_VILLALOBOS_SALINAS',
  'sistemas5@kabzo.org': 'JESUS_ALFONSO_AYALA_FLORES',
  'tesoreria1@kabzo.org': 'CARMEN_GABRIELA_GONZALEZ_GONZALEZ',
  'tesorerias3@kabzo.org': 'SERGIO_SALAS_SALAZAR',
  'tesoreriag@kabzo.org': 'LIZETH_VERONICA_AYALA_AGUILAR',
  'tesoreriar@kabzo.org': 'YOWALY_VAZQUEZ_VALDEZ',
  'tesoreria7@kabzo.org': 'CARLOS_ALMAGUER_SALAZAR',
  'tesoreria3@kabzo.org': 'MARIA_DOLORES_VILLAGOMEZ',
  'entregas.guadalajara1@kabzo.org': 'JESSICA_LILIANA_LAU_CONTRERAS',
  'tesoreria5@kabzo.org': 'CYNTHIA_JANETH_ALANIS_SUAREZ',
  'tesoreria8@kabzo.org': 'ARNOLD_ANTONIO_VAZQUEZ_VALDES',
  'facturacion.asesores.pdc@gmail.com': 'JUAN_JESUS_GARCIA_ALANIS',
  'verificador@kabzo.org': 'AZAEL_RANGEL_RODRIGUEZ',
  'verificador2@kabzo.org': 'DAMARIS_TORRES_OLIVARES',
  'verificador1@consultoriavrf.com': 'JULIAN_LOZANO_GARZA',
  'verificador3@consultoriavrf.com': 'FLOR_THALIA_MEDINA_GALLEGOS',
  'verificador5@consultoriavrf.com': 'LUIS_GERARDO_PEÑA_BELTRAN',
  'verificador8@consultoriavrf.com': 'ANDREA_FLORES_LOZANO',
  'verificador6@consultoriavrf.com': 'DANIELA_NOHEMI_GONZALEZ_TORRES',
  'verificador10@consultoriavrf.com': 'MANUEL_ENRIQUE_MENDOZA_ESQUIVE',
  'verificador9@consultoriavrf.com': 'BRISEIDA_JACKELINE_ZAPATA_SANCHEZ',
  'verificador4@consultoriavrf.com': 'NAZIRA_YARESSI_JAIME_MARTINEZ',
  'verificador11@kabzo.org': 'PEDRO_SUAREZ_BARRON',
}

var DIR_EJECUTIVOS = {
'paula.paez@afirme.com>': 'NOHEMI_PAEZ',
'cesar.guadarrama@afirme.com>': 'CESAR_PEREZ',
'kathiaelizondo@afirme.com>': 'KATHIA_ELIZONDO',
'hamorales@bb.com.mx>': 'HARLY_MORALES',
'raquel.alvarez@banregio.com>': 'RAQUEL_ALVAREZ',
'bcapymes01suc1582@santander.com.mx>': 'CESAR_ORTIZ',
'jomanzur@bb.com.mx>': 'JORGE_MANZUR',
'yesenia.trevino@banregio.com>': 'YESENIA_TREVIÑO',
'alagomez@santander.com.mx>': 'ALAN_GOMEZ',
'daniel.ocura.ramos@banorte.com>': 'DANIEL_OCURA',
'juan.sanchez.sustaita@banorte.com>': 'ANTONIO_SANCHEZ',
'carlos.munoz@banregio.com>': 'CARLOS_MUÑOZ',
'karla.maldonado@banregio.com>': 'KARLA_MALDONADO',
'eduardo.valencia@bbva.com>': 'EDUARDO_VALENCIA',
'afernandezg@monex.com.mx>': 'ARMANDO_FERNANDEZ',
'joanluna@scotiabank.com.mx>': 'ANTONIO_LUNA',
'kevin.partida.guerrero@banorte.com>': 'KEVIN_PARTIDA',
'edihyashiel.romero@bbva.com>': 'EDIH_ROMERO',
'oscareduardo.marroquin@bbva.com>': 'OSCAR_MARROQUIN',
'roberto.sanchez@hsbx.com.mx>': 'ROBERTO_SANCHEZ',
'rogeliocesar.gonzalez@bbva.com>': 'ROGELIO_GONZALEZ',
'lorenalizeth.zaragoza@bbva.com>': 'LORENA_ZARAGOZA',
'directorsuc3987@santander.com.mx>': 'HUGO_RIVAS',
}

var DIR_PPROVEEDORES = {

}

var DIR_COBRANZA = [
  'soporte1@gcorporativa.com.mx>',
  'ASESOR086@outlook.com>',
  'soporte2@gcorporativa.com.mx>',
  'soporte3@gcorporativa.com.mx>',
  'asesoriaintegral919@gmail.com>',
  'facturacion.asesores.pdc@gmail.com>',
  'facturacion@kabzo.org>',
  'facturacion2@kabzo.org>',
  'contacto1@dosasoluciones.com>',
  'lquintana@transval.mx>',
  'contacto@kabzo.org>',
  'operacion@stc.com.mx>',
  'superamaya.vega@hotmail.com>',
  'facturacion1@kabzo.org>',
  'soluciones.saldana@hotmail.com>',
  'contabilidad14@kabzo.org>',
  'asesoria.admon87@gmail.com>',
  'asesores@kabzo.org>',
  'papeleriaa1956@gmail.com>',
  'asesorescarso1@gmail.com>',
  'gproyecto569@gmail.com>',
  'contabilidad1@kabzo.org>',
  'operaciones.ly@aryaconsulting.org>',
  'operaciones.2@aryaconsulting.org>',
  'cobranza@kabzo.org>',
  'solicitudes1956@gmail.com>',
  'admin@osasociados.com>',
  'asesoria.admon87@gmail.com>',
  'gproyecto569@gmail.com>',
  'asesoriaintegral919@gmail.com>',
  'operacionfinance@gmail.com>',
  'apoyomovimientos2023.m@gmail.com>',
  'gestiondeproyectos40@gmail.com>',
]
