// SEMANAS BONOS FORMULA:

`=SWITCH(
(NUM.DE.SEMANA(HOY()+SWITCH(DIASEM(HOY(),2),
  1,(4),
  2,(3),
  3,(2),
  4,(1),
  5,(0),
  "INVALIDO")
) - 
NUM.DE.SEMANA(FECHA(AÑO(
HOY()+SWITCH(DIASEM(HOY(),2),
  1,(4),
  2,(3),
  3,(2),
  4,(1),
  5,(0),
  "INVALIDO")
),MES(
HOY()+SWITCH(DIASEM(HOY(),2),
  1,(4),
  2,(3),
  3,(2),
  4,(1),
  5,(0),
  "INVALIDO")
),
SI(RESIDUO(DIA(HOY()+SWITCH(DIASEM(HOY(),2),
  1,(4),
  2,(3),
  3,(2),
  4,(1),
  5,(0),
  "INVALIDO")),7)=0,7,
RESIDUO(DIA(HOY()+SWITCH(DIASEM(HOY(),2),
  1,(4),
  2,(3),
  3,(2),
  4,(1),
  5,(0),
  "INVALIDO")),7))
))) + 1,
1,"PRIMERA SEMANA
NO APLICA BONO ESTA SEMANA",
2,"SEGUNDA SEMANA
BONO MENSUAL (PRODUCTIVIDAD)",
3,"TERCER SEMANA
BONO EMPLEADO DEL MES",
4,"CUARTA SEMANA
BONOS: TRASLADO, DESPENSA Y LEALTAD",
5,"QUINTA SEMANA
NO APLICA BONO ESTA SEMANA",
"INVALIDO")`



// SEMANA NOMINA:

`="SEMANA "&NUM.DE.SEMANA(FECHA(AÑO(HOY()),MES(HOY()-DIASEM(HOY())+2),DIA(HOY()-DIASEM(HOY())+2)))&"
DEL "&DIA(HOY()-DIASEM(HOY())+2)&" DE "&
SWITCH(MES(HOY()-DIASEM(HOY())+2),
1,"ENERO",
2, "FEBRERO",
3, "MARZO",
4, "ABRIL",
5, "MAYO",
6, "JUNIO",
7, "JULIO",
8, "AGOSTO",
9, "SEPTIEMBRE",
10, "OCTUBRE",
11, "NOVIEMBRE",
12, "DICIEMBRE",
"INVALIDO")
&" AL "&DIA(HOY()-DIASEM(HOY())+6)&" DE "&
SWITCH(MES(HOY()-DIASEM(HOY())+6),
1,"ENERO",
2, "FEBRERO",
3, "MARZO",
4, "ABRIL",
5, "MAYO",
6, "JUNIO",
7, "JULIO",
8, "AGOSTO",
9, "SEPTIEMBRE",
10, "OCTUBRE",
11, "NOVIEMBRE",
12, "DICIEMBRE",
"INVALIDO")`
